[#11] добавил файл models.py , таблица температуры
lsd-maddrive/climate_chamber pull request #21
Opened 2024-03-27 09:21 UTC by PanDanil777

2024-03-27 13:19 UTC, serykhelena requested changes

2024-03-27 13:19 UTC, serykhelena commented on climate_chamber/database/models.py
> +    id = Column(Integer, primary_key=True)
Добавить autoincrement=True, index=True
Почитать, за что это отвечает

2024-03-29 08:28 UTC, PanDanil777 commented on climate_chamber/database/models.py
> +    value = Column(String)
key отвечает за хранение уникального ключа, а value может содержать дополнительные данные или описание какое-то. вообще мне кажется можно убрать его и переборщил с добавлением его.

2024-04-02 19:19 UTC, serykhelena requested changes

2024-04-02 19:19 UTC, serykhelena commented on climate_chamber/database/models.py
> +    timestamp = Column(DateTime, default=datetime.datetime.now)
Посмотри про `onupdate` аргумент 
И под доп функции в sqlalchemy (`now()`)

2024-04-02 19:19 UTC, serykhelena commented on climate_chamber/database/models.py
> +    tablename = 'temperature'
tablename не верно написан, не хватает нижних подчёркиваний

2024-04-03 11:46 UTC, serykhelena requested changes

2024-04-03 11:46 UTC, serykhelena commented on climate_chamber/database/models.py
> +    timestamp = Column(DateTime, default=datetime.datetime.now, onupdate=datetime.now)
Так функция now не будет работать

2024-04-06 18:33 UTC, serykhelena requested changes

2024-04-06 18:33 UTC, serykhelena commented on climate_chamber/database/models.py
> +    timestamp = Column(DateTime, default=datetime.datetime.now, onupdate=datetime.now)
Так должно работать 
```
from sqlalchemy.sql import functions as func

...
timestamp = Column(DateTime(timezone=True), onupdate=func.now()) 
```

2024-04-08 11:01 UTC, serykhelena approved these changes

2024-04-08 11:02 UTC, merged